#!/bin/bash

PROMPT="   Open bookmark "
PROMPT_ADD="   Add bookmark "

DMENU_OPT=" -i -nb #1F222D -nf #929496 -sb #929496 -sf #1F222D -fn Iosevka:style=Regular:pixelsize=13"    
DMENU="dmenu -l 10 $DMENU_OPT"

bmFile="$HOME/.config/todo/bm_url.txt"
if [ ! -f $bmFile ]; then
     mkdir -p "$(dirname "$bmFile")" && touch "$bmFile"
     echo "add" >> $bmFile
 else
     touch "$bmFile"
fi    
    
url=$( cat $bmFile | $DMENU -p "$PROMPT" | sed "s/ .*//")

if [[ "$url" == "add" ]]; then
    url=$( $DMENU -p "$PROMPT_ADD" "$@" < "$bmFile" )
    if [[ "$url" == "add" ]] || [[ -z "$url" ]]; then 
        exit 
    fi
    echo "$url" >> "$bmFile"
    xdg-open $url 2> /dev/null
else
    if [[ -n "$url" ]]; then
      xdg-open $url 2> /dev/null
    fi  
fi    

