#!/bin/bash

PROMPT="   Open bookmark "

DMENU_OPT=" -i -nb #2E3440 -nf #929496 -sb #929496 -sf #2E3440 -fn Iosevka:style=Regular:pixelsize=13"    
DMENU="dmenu -l 10 $DMENU_OPT"

file="$HOME/.config/todo/bm_url.txt"

touch "$file"
chosen=$( cat $file | $DMENU -p "$PROMPT" | sed "s/ .*//")

if [ -n "$chosen" ]; then
    xdg-open $chosen 2> /dev/null
fi

