#!/bin/bash
#viyoriya

PROMPT="   Bookmarks "
PROMPT_ADD="   Add URL "
PROMPT_DEL="   Delete URL "
PROMPT_LIST="   Open URL "
DMENU_HORIZ="dmenu -i"
DMENU_VERT="dmenu -i -l 15 "
bmFile="$HOME/.config/todo/bm_url.txt"

[[ ! -f "$bmFile" ]] && mkdir -p "$(dirname "$bmFile")" && touch "$bmFile"

while true; do
    mode=$(printf "add\ndel\nlist" | $DMENU_HORIZ -p "$PROMPT")
    [[ -z "$mode" ]] && exit

    case "$mode" in
        add)
            new_url=$( : | $DMENU_HORIZ -p "$PROMPT_ADD" )
            if [[ -n "$new_url" ]]; then
                echo "$new_url" | cat - "$bmFile" > "$bmFile.tmp" && mv "$bmFile.tmp" "$bmFile"
            fi
            ;;

        del)
            selection=$(awk '{print NR ". " $0}' "$bmFile" | $DMENU_VERT -p "$PROMPT_DEL")
            if [[ -n "$selection" ]]; then
                line_num=$(echo "$selection" | cut -d'.' -f1)
                sed -i "${line_num}d" "$bmFile"
            fi
            ;;

        list)
            choice=$( < "$bmFile" $DMENU_VERT -p "$PROMPT_LIST")
            if [[ -n "$choice" ]]; then
                url=$(echo "$choice" | awk '{print $1}')
                [[ ! "$url" =~ ^[a-zA-Z0-9]+:// ]] && url="https://$url"
                xdg-open "$url" 2> /dev/null
            fi
            ;;
    esac
done

