#!/bin/bash

COIN=(ETC ADA DOT XRP ANKR DOGE SHIB)

i=0;

echo "COIN    PRICE        " 
echo "=====   ============="

for coin in "${COIN[@]}"; do 
    tmpVal="$(curl -s gbp.rate.sx/1$coin)"
    if [[ "$i" -gt 4 ]]; then
        echo $coin"    "$tmpVal 
    else
        echo $coin"     "$tmpVal 
    fi
    
    i=$((i+1))
done


