#!/usr/bin/env bash
#viyoriya - map to ShiftKey+XK_d in dwm

PROMPT="   Scripts "
DMENU="dmenu -l 12 "

script=$( cd /usr/local/bin/ && find d_* | $DMENU -p "$PROMPT")
[[ -n "$script" ]] && "$script"

#binPath='/usr/local/bin/'
#script=$( cd $binPath && find d_* | $DMENU -p "$PROMPT")
