#!/bin/bash
#viyoriya - map to Modkey+ShiftKey+XK_d in dwm

PROMPT="   Scripts "

#DMENU="dmenu -l 10 "
DMENU="dmenu " #bored of dropdown for 6 years use

script=$( cd /usr/local/bin/ && find d_* | $DMENU -p "$PROMPT")
[[ -n "$script" ]] && source "$script" #Bloody shellcheck throws error grrrr 


