#!/bin/bash

PROMPT="   Scripts "

DMENU_OPT=" -i -nb #1F222D -nf #929496 -sb #929496 -sf #1F222D -fn Iosevka:style=Regular:size=11"    
DMENU="dmenu -l 10 $DMENU_OPT"

script=$( cd /usr/local/bin/ && \ls -1 d_* | $DMENU -p "$PROMPT")

if [[ $script ]]; then 
    . $script
fi

