#!/bin/bash
#viyoriya - provide permission in sudoers for mount

PROMPT="   Mount HDD "
DMENU="dmenu -l 10 "

[[ $(mountpoint -q -- "/mnt") ]] &&  sudo umount /mnt

openDrive(){
    if [ -n "$1" ] ; then
        sudo mount "/dev/$1" /mnt
        notify-send -u low "/dev/$1 mounted in /mnt"
    fi    
}
 
openDrive "$(\lsblk -do name,tran | awk '$2=="usb" {print $1}' | $DMENU -p "$PROMPT" )"
