#!/bin/bash

PROMPT="   Mount HDD "

DMENU_OPT=" -i -nb #1F222D -nf #929496 -sb #929496 -sf #1F222D -fn Iosevka:style=Regular:pixelsize=13"    
DMENU="dmenu -l 10 $DMENU_OPT"

if [ -d "/mnt/home/" ]; then
#    echo "  :::: un mounting the drive ::::"
    sudo umount /mnt/
fi

openDrive(){
    sudo mount "$1" /mnt/
    st -e &
}
 
openDrive $(\ls /dev/sd* | grep '/dev/sd[a-z][0-9]' | $DMENU -p "$PROMPT" )

#exit 0

#hdd=$(\ls /dev/sd* | grep '/dev/sd[b-z][0-9]' | $DMENU )
#\ls /dev/s* | grep '/dev/s[a-z][b-z][0-9]'
