#!/bin/bash
#viyoriya - provide permission in sudoers for mount

PROMPT="   Mount local HDD "
DMENU="dmenu -l 10 "

[[ $(mountpoint -q -- "/mnt") ]] &&  sudo umount /mnt

openDrive(){
    echo $1
    if [ -n "$1" ] ; then
        sudo mount "/dev/$1" /mnt
        notify-send -u low "  /dev/$1 mounted in /mnt"
    fi    
}
 
openDrive $(\lsblk -T=fstype -o name,fstype,label,type,mountpoint | awk '/s[a-z][a-z][0-9]/ && $3!="part" && $5!="/" &&  $5!="[SWAP]" {print $1,$3}' | $DMENU -p "$PROMPT" )

