#!/bin/bash
#viyoriya

PROMPT="   Login id " 

#DMENU_OPT=" -i -nb #1F222D -nf #929496 -sb #929496 -sf #1F222D -fn Iosevka:style=Regular:size=10"    
#DMENU="dmenu -l 10 $DMENU_OPT"
DMENU="dmenu -l 10 "

password=$(find ~/.password-store/ -type f -name '*.gpg' |
	cut -d'/' -f5- | rev | cut -f 2- -d '.' | rev | $DMENU -p "$PROMPT" )

[ -n "$password" ] && pass show -c "$password"
