#!/bin/bash
# viyoriya -  center and password patch should be applied in dmenu else it doesnt work

# =================================================
#========== password - store is hard coded ========
# =================================================

# DEBUG: Log all output and errors to /tmp/dpass_debug.log
#exec > /tmp/dpass_debug.log 2>&1
#set -x  # Print each command before executing it

PASSWORD_STORE_DIR="$HOME/.local/share/.password-store"
PROMPT="   Login: "
DMENU="dmenu -i -c -l 10 -p"
DMENU_PWD="dmenu -i -c -P -p"
MASTER_PROMPT="  Enter Master Pwd : "

# Set the TTY for GPG
export GPG_TTY=$(tty)

# Start gpg-agent if it isn't running
if ! pgrep -x -u "$USER" gpg-agent >/dev/null; then
  gpg-connect-agent /bye
fi

selection=$(find "$PASSWORD_STORE_DIR" -type f -name "*.gpg" -printf "%P\n" | sed 's/\.gpg$//' | $DMENU "$PROMPT")
[ -z "$selection" ] && exit 0

passphrase=$(echo "" | $DMENU_PWD "$MASTER_PROMPT" | tr -d '\n')
[ -z "$passphrase" ] && exit 1

if echo "$passphrase" | gpg --batch --quiet --passphrase-fd 0 --pinentry-mode loopback -d "$PASSWORD_STORE_DIR/$selection.gpg" | head -n 1 | xclip -selection clipboard; then
  notify-send "Pwd for $selection in clipboard"
  # Optional: Clear clipboard after 15 seconds
  (sleep 15 && xclip -selection clipboard /dev/null) &
else
  notify-send "Error: Decryption failed"
fi
