#!/bin/bash

PROMPT="   Google Search " 

DMENU_OPT=" -i -nb #2E3440 -nf #929496 -sb #929496 -sf #2E3440 -fn Iosevka:style=Regular:pixelsize=13"    
DMENU="dmenu $DMENU_OPT"

URL='http://www.google.com/search?q='
QUERY=$( echo '' |  $DMENU -p "$PROMPT" )

if [ -n "$QUERY" ]; then
  xdg-open "${URL}${QUERY}" 2> /dev/null
fi

