#!/bin/bash
# viyoriya - Google Search 

#DMENU_OPT=" -i -nb #1F222D -nf #929496 -sb #929496 -sf #1F222D -fn Iosevka:style=Regular:size=10"    
#DMENU="dmenu $DMENU_OPT"

PROMPT="   Google Search "
DMENU="dmenu -p"
URL='http://www.google.com/search?q='

QUERY=$(dmenu -p "$PROMPT" < /dev/null)

if [ -n "$QUERY" ]; then
  ENCODED_QUERY=$(echo "$QUERY" | sed 's/ /+/g')
  
  xdg-open "${URL}${ENCODED_QUERY}" 2> /dev/null &
fi



