#!/bin/bash
#viyoriya

PROMPT="   Start Timer "
timerFile="/tmp/.timerFile" #move it to ~/.config/ so it will be persisted even after reboot

MINS=$(printf '%s min\n' {1..60})
HOURS=$(printf '%s hr\n' {1..8})
timer=$(printf "%s\n%s" "$MINS" "$HOURS" | dmenu -i -p "$PROMPT")

if [ -n "$timer" ]; then
    
    timeValue=$(echo "$timer" | awk '{print $1}')
    minsOrhrs=$(echo "$timer" | awk '{print $2}')

    if [[ "$minsOrhrs" == "min" ]]; then
        [ -f $timerFile ] && rm $timerFile
        echo "$(date +'%H:%M') $timeValue minutes" >> $timerFile
    elif [[ "$minsOrhrs" == "hr" ]]; then
        [ -f $timerFile ] && rm $timerFile
        echo "$(date +'%H:%M') $((timeValue * 60)) minutes" >> $timerFile
    else
        exit 0
    fi    
else
    exit 0   
fi    



