#!/bin/bash
#viyoriya

timerFile="/tmp/.timerFile" #move it to ~/.config/ so it will be persisted even after reboot

timer(){
    if [ -f $timerFile ]; then
        timer=$(cat $timerFile)
        tmpTime=$(date -d "$timer" +'%H:%M')
        timerSec=$(date +%s -d "$tmpTime")
        now=$(date +%s)
        timeDiff=$(( (timerSec - now) / 60 ))
        if [ "$timeDiff" -ge "0" ]; then
            printf "%s" "^c#5E81AC^ ^d^$timeDiff Min"
        else
            notify-send -u low "Timer" "done !!!" -i  ~/.config/dwm/util/dwm_logo.png
            #aplay ~/.config/dwm/util/mixkit-happy-bell-alert-601.wav
            for i in {1..5}; do aplay ~/.config/dwm/util/mixkit-happy-bell-alert-601.wav > /dev/null 2>&1  ; done  
            rm $timerFile
        fi
    fi    
}

timer
