#!/bin/sh

PROMPT="   Add task  "

DMENU_OPT=" -i -nb #1F222D -nf #929496 -sb #929496 -sf #1F222D -fn Iosevka:style=Regular:pixelsize=13"    

file="$HOME/.config/todo/todo.txt"
if [ ! -f $file ]; then
     mkdir -p "$(dirname "$file")" && touch "$file"
 else
     touch "$file"
fi    
height=$(wc -l "$file" | awk '{print $1}')

cmd=$(dmenu -l "$height" -p "   [$height] $PROMPT" $DMENU_OPT "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
        opt=$(echo -e "Yes\nNo" | dmenu -i -p "   [$height]    Delete this task  " $DMENU_OPT)
           if [ "$opt" == "Yes" ];then 
                grep -v "^$cmd\$" "$file" > "$file.$$"
	    	    mv "$file.$$" "$file"
                height=$(( height - 1 ))
           fi
    else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi
    
	cmd=$(dmenu -l "$height" -p "   [$height] $PROMPT" $DMENU_OPT "$@" < "$file")
done

#exit 0
