#!/bin/bash
#viyoriya

PROMPT="   Add task  "

file="$HOME/.config/todo/todo.txt"
if [ ! -f "$file" ]; then
     mkdir -p "$(dirname "$file")" && touch "$file"
 else
     touch "$file"
fi    
height=$(wc -l "$file" | awk '{print $1}')

cmd=$(dmenu -l "$height" -p "   [$height] $PROMPT" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
        opt=$(echo -e "Yes\nNo" | dmenu -i -p "   [$height]    Delete this task  " )
           if [ "$opt" == "Yes" ];then 
                grep -v "^$cmd\$" "$file" > "$file.$$"
	    	    mv "$file.$$" "$file"
                height=$(( height - 1 ))
           fi
    else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi
    
	cmd=$(dmenu -l "$height" -p "   [$height] $PROMPT" "$@" < "$file")
done

#exit 0
