#!/bin/bash
#viyoriya  provide permissions in the sudoers: %wheel ALL=(ALL) NOPASSWD: /usr/bin/umount, /usr/bin/rmdir

PROMPT="   Unmount USB "
DMENU="dmenu -i -l 10"

close_drive() {
    local target="$1"
    if [[ -n "$target" ]]; then
        if sudo umount "$target"; then
            sudo rmdir "$target" 2>/dev/null
            notify-send -u low "$target Unmounted"
        else
            notify-send -u critical "$target is likely busy"
        fi
    fi
}

selection=$(findmnt -lo TARGET | grep "^/mnt/" | $DMENU -p "$PROMPT")

close_drive "$selection"

